In [2]:
import torch
import torch.nn as nn

In [4]:
# 卷积
kernel = torch.tensor([[1, 0, 1],[0, 1, 0],[1, 0, 1]])
image = torch.LongTensor([
    [1, 8, 4, 2, 5],
    [6, 7, 5, 7, 6],
    [5, 0, 8, 3, 5],
    [7, 9, 1, 0, 7],
    [2, 3, 9, 8, 3],
])

kernel = kernel.unsqueeze(0).unsqueeze(0).float()
image = image.unsqueeze(0).unsqueeze(0).float()

conv = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1)

conv.weight = nn.Parameter(kernel)
nn.init.ones_(conv.bias)

print(kernel)
print(image)

print(conv(image))

tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]])
tensor([[[[1., 8., 4., 2., 5.],
          [6., 7., 5., 7., 6.],
          [5., 0., 8., 3., 5.],
          [7., 9., 1., 0., 7.],
          [2., 3., 9., 8., 3.]]]])
tensor([[[[ 9., 20., 19., 14., 13.],
          [15., 26., 19., 30., 12.],
          [22., 20., 32., 23., 13.],
          [11., 34., 16., 26., 19.],
          [12., 12., 19., 17.,  4.]]]], grad_fn=<ThnnConv2DBackward0>)


In [6]:
# 池化
print(image)

max_pool = nn.MaxPool2d(kernel_size=2, stride=1)
avg_pool = nn.AvgPool2d(kernel_size=2, stride=1)

print(max_pool(image))
print(avg_pool(image))

tensor([[[[1., 8., 4., 2., 5.],
          [6., 7., 5., 7., 6.],
          [5., 0., 8., 3., 5.],
          [7., 9., 1., 0., 7.],
          [2., 3., 9., 8., 3.]]]])
tensor([[[[8., 8., 7., 7.],
          [7., 8., 8., 7.],
          [9., 9., 8., 7.],
          [9., 9., 9., 8.]]]])
tensor([[[[5.5000, 6.0000, 4.5000, 5.0000],
          [4.5000, 5.0000, 5.7500, 5.2500],
          [5.2500, 4.5000, 3.0000, 3.7500],
          [5.2500, 5.5000, 4.5000, 4.5000]]]])
