## Numpy 使用讲解

### 创建数组

In [4]:
import numpy as np

vec = np.array([1, 2, 3, 4])

print(vec)

[1 2 3 4]


In [5]:
matrix = np.array([
    [1, 'Tim'],
    [2, 'Bob'],

])
print(matrix)

[['1' 'Tim']
 ['2' 'Bob']]


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((4, 4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 创建随机数组

In [28]:
np.random.randint(0, 10, (2, 2))

array([[3, 9],
       [4, 2]])

In [31]:
np.random.seed(1)
np.random.randint(0, 10, 5)

array([5, 8, 9, 5, 0])

In [33]:
np.random.random(10)

array([0.19810149, 0.80074457, 0.96826158, 0.31342418, 0.69232262,
       0.87638915, 0.89460666, 0.08504421, 0.03905478, 0.16983042])

In [45]:
np.random.normal(loc=0, scale=4, size=10)

array([ 3.62980464, -8.53933927,  3.2673887 ,  4.73668524, -0.81792226,
       -0.44337784,  5.65793091, -5.66658001,  2.69405383, -3.08917769])

### 获取Numpy属性

In [58]:
a = np.arange(15)
b = np.reshape(a, newshape=(3, 5))

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [57]:
c = np.reshape(a, newshape=(5, -1))
print(c)
print(c.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
2


### Numpy 数组索引

In [59]:
import numpy as np

matrix = np.array([
    [1, 4, 7],
    [2, 5, 8],
])
print(matrix[0, 1])

4


### 切片

In [60]:
matrix = np.array([
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])
print(matrix[:, 1])
print(matrix[:, 0:2])
print(matrix[1:3, :])
print(matrix[1:3, 0:2])

[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[2 5 8]
 [3 6 9]]
[[2 5]
 [3 6]]


### 矩阵运算

In [66]:
import numpy as np

one_matrix = np.ones([3, 3])
eye_matrix = np.eye(3, k=0) # k表示与主对角线的偏移度，k>0往右上偏移，k<0往左下偏移

print(one_matrix)
print('-----------')
print(eye_matrix)
print('-----------')
print(one_matrix - eye_matrix)
print('-----------')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
-----------


In [67]:
st_matrix = np.array([
    [1, 4, 9],
    [4, 16, 25],
    [36, 49, 64]
])
np.sqrt(st_matrix)

array([[1., 2., 3.],
       [2., 4., 5.],
       [6., 7., 8.]])

In [78]:
A3x2 = np.array([
    [1, 2],
    [4, 6],
    [3, 2]
])
B2x4 = np.array([
    [1, 2, 3, 4],
    [4, 6, 5, 3]
])

C3x4 = np.dot(A3x2, B2x4)

print(A3x2.shape)
print(B2x4.shape)
print(C3x4.shape)

print(C3x4)

(3, 2)
(2, 4)
(3, 4)
[[ 9 14 13 10]
 [28 44 42 34]
 [11 18 19 18]]


In [83]:
print(A3x2)
print(A3x2.T)
print(np.transpose(A3x2))
A3x2.flatten()

[[1 2]
 [4 6]
 [3 2]]
[[1 4 3]
 [2 6 2]]
[[1 4 3]
 [2 6 2]]


array([1, 2, 4, 6, 3, 2])

In [80]:
# 求举证的逆
import numpy as np
import numpy.linalg as lg

A = np.array([
    [2, 4],
    [4, 6]
])
invA = lg.inv(A)

print(invA)

[[-1.5  1. ]
 [ 1.  -0.5]]


### 数据类型的转换

In [84]:
vertor = np.array(['1', '2', '3', '4'])
int_vertor = vertor.astype(dtype=int)

print(int_vertor)

[1 2 3 4]


In [90]:
num_vertor = np.array([2, 4, 6, 8])
print(num_vertor.mean())
print(num_vertor.sum())
print(num_vertor.max())
print(num_vertor.min())
print(np.median(num_vertor))

5.0
20
8
2
5.0


In [94]:
num_vertor = np.array([
    [2, 4, 6, 8],
    [4, 6, 10, 12]
])
print(num_vertor.mean(axis=1))
print(num_vertor.sum(axis=1))
print(num_vertor.max(axis=1))
print(num_vertor.min(axis=1))
print(np.median(num_vertor, axis=1))

[5. 8.]
[20 32]
[ 8 12]
[2 4]
[5. 8.]


### Numpy中的arg运算

In [103]:
idx1 = np.argmax([3, 1, 6, 8, 2, 5])
idx2 = np.argmin([3, 1, 6, 8, 2, 5])

seq_ver = [1, 2, 3, 4, 5]
np.random.shuffle(seq_ver)
print(seq_ver)
print(idx1)
print(idx2)

sort_idx = np.argsort(seq_ver)

print(sort_idx)

[5, 2, 4, 3, 1]
3
1
[4 1 3 2 0]


### FancyIndexing

In [105]:
import numpy as np

X = np.arange(15)
ind = [3, 5, 8]
print(X)
print(X[ind])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 5 8]


In [106]:
np.random.shuffle(X)
print(X)
ind = np.array([[0, 2], [1, 3]])
print(X[ind])

[ 0  3 14  1 10  8  6  2 11 13  4  5  9 12  7]
[[ 0 14]
 [ 3  1]]


In [108]:
x = np.arange(16)
X = x.reshape(4, -1)
print(X)

row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

print(X[row, col])
print(X[1:3, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  6 11]
[[ 5  6  7]
 [ 9 10 11]]


### Numpy数组比较

In [110]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [1, 3, 5],
    [1, 4, 7]
])

M = matrix == 3
print(M)

[[False False  True]
 [False  True False]
 [False False False]]


In [115]:
# matrix[:, 2] = [3 5 7]
second_col_3 = (matrix[:, 0] == 1)
print(second_col_3)

print(matrix[second_col_3])

[ True  True  True]
[[1 2 3]
 [1 3 5]
 [1 4 7]]


In [119]:
print(np.all((matrix > 0)))             # 是不是所有的都 > 0
print(np.any((matrix > 3)))             # 是不是存在 > 3
print(np.count_nonzero((matrix > 3)))   # 非 0(False) 的元素个数

True
True
3
