## Tensor 进阶知识

### Tensor的组合与分块

组合：`torch.cat(), torch.stack()` 

分块：`torch.chunk(), torch.spilk()`

In [2]:
import torch

In [3]:
a = torch.Tensor([[1, 2], [3, 4]])
b = torch.Tensor([[5, 6], [7, 8]])

In [4]:
c1 = torch.cat([a, b], 0)
c2 = torch.cat([a, b], 1)

print(c1)
print(c2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [9]:
d1 = torch.stack([a, b], 0)
d2 = torch.stack([a, b], 1)
d3 = torch.stack([a, b], 2)

'''
1.
[[1, 2], [3, 4]] cat [[5, 6], [7, 8]] = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
2.
[1, 2] cat [5, 6] = [[1, 2], [5, 6]]
[3, 4] cat [7, 8] = [[3, 4], [7, 8]]
=>
[[[1, 2], [5, 6]],[[3, 4], [7, 8]]]
3.
[[1, 5], [2, 6], [3, 7], [4, 8]]
'''
print(d1)
print(d2)
print(d3)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])
tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])


In [10]:
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])

In [14]:
#TODO Review
e1 = a.chunk(2, 0)
e2 = a.chunk(2, 1)

f1 = a.split(2, 0)
f2 = a.split(2, 1)

print(e1)
print(e2)

print(f1)
print(f2)

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]))
(tensor([[1., 2.],
        [4., 5.]]), tensor([[3.],
        [6.]]))
(tensor([[1., 2., 3.],
        [4., 5., 6.]]),)
(tensor([[1., 2.],
        [4., 5.]]), tensor([[3.],
        [6.]]))


### Tensor 的索引与变形

In [20]:
a = torch.Tensor([[0, 1], [2, 3]])

print(a[1])
print(a[0, 1])

print(a > 0)
print(a[a > 0])
print(torch.masked_select(a, a > 0))

# 获取非0元素的坐标
print(torch.nonzero(a))

tensor([2., 3.])
tensor(1.)
tensor([[False,  True],
        [ True,  True]])
tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([[0, 1],
        [1, 0],
        [1, 1]])


In [23]:
# where & clamp
full_one = torch.full_like(a, 1)
print(torch.where(a > 1, full_one, a))

tensor([[0., 1.],
        [1., 1.]])


In [26]:
g = a.clamp(1, 2)
print(g)

tensor([[1., 1.],
        [2., 2.]])


In [31]:
#### view, resize, reshape
a = torch.arange(1, 5)

# view
b1 = a.view(2, 2)
b2 = a.resize(4, 1) #deprecated
b3 = a.reshape(4, 1)

print(a)
print(b1)
print(b2)
print(b3)


tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])


C:\ProgramData\Anaconda3\lib\site-packages\torch\_tensor.py:493: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [34]:
b1[0, 0] = 6
print(a)
b2[0, 0] = 7
print(a)
b3[0, 0] = 8
print(a)

tensor([6, 2, 3, 4])
tensor([7, 2, 3, 4])
tensor([8, 2, 3, 4])


In [35]:
a.resize_(2, 3) # 直接改变a

print(a)

tensor([[8, 2, 3],
        [4, 0, 0]])


In [42]:
### transpose, permute
a = torch.tensor([
    [[1, 2],[3, 4]],
    [[5, 6],[7, 8]]
])

print(a)
'''

[ [[1, 2], [3, 4]],
  [[5, 6], [7, 8]] ]
------T--------
[ [[1, 2], [5, 6]],
  [[3, 4], [7, 8]] ]
'''

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [75]:
# 按照不同的维度进行转置
b1 = torch.transpose(a, 0, 1)


print(a)
print(b1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [94]:
# 完成 [N, C, H, W] -> [N, H, W, C]
img_set = torch.Tensor(4, 3, 28, 24)
print(img_set.shape)
# transpose
img_set1 = img_set.transpose(1, 3).transpose(1, 2)
print(img_set1.shape)

img_set2 = img_set.permute(0, 2, 3, 1)
print(img_set2.shape)


torch.Size([4, 3, 28, 24])
torch.Size([4, 28, 24, 3])
torch.Size([4, 28, 24, 3])


In [61]:
# squeeze & unsequeeze
bias = torch.tensor([1, 2, 3])
img = torch.randint(1, 4, (4, 3, 32, 32))

bias = bias.unsqueeze(0).unsqueeze(2).unsqueeze(3)
bias = bias.expand(4, 3, 32, 32)
print(bias.shape)
print(img.shape)

img = img + bias
print(img.shape)


torch.Size([4, 3, 32, 32])
torch.Size([4, 3, 32, 32])
torch.Size([4, 3, 32, 32])


In [72]:
bias = torch.randint(1, 4, (1, 4, 1, 1))

print(bias.shape)
print(bias.squeeze().shape)
print(bias.squeeze(0).shape)
print(bias.squeeze(0).squeeze(1).shape)
print(bias.squeeze(0).squeeze(1).squeeze(1).shape)


torch.Size([1, 4, 1, 1])
torch.Size([4])
torch.Size([4, 1, 1])
torch.Size([4, 1])
torch.Size([4])


In [90]:
# expand -1 表示维度不变
bias = torch.randint(1, 4, (4,))

print(bias, bias.shape)
bias = bias.expand(1, 4)
bias = bias.expand(2, 4)
bias = bias.expand(1, 2, 4)
print(bias, bias.shape)

tensor([2, 1, 1, 2]) torch.Size([4])
tensor([[[2, 1, 1, 2],
         [2, 1, 1, 2]]]) torch.Size([1, 2, 4])


### 矩阵操作

In [97]:
# 降维
img = torch.rand(4, 28*28)

x = torch.rand(4, 28*28)
w = torch.rand(512, 28*28)

# 从 784 -> 512
torch.matmul(x, w.t()).shape # 4 * 512 二维亦可使用 mm

torch.Size([4, 512])

In [101]:
# power 求次方
a = torch.full([2, 2], 3)
print(a)
a = a.pow(2)
print(a)
a = a.sqrt()
print(a)
a = a**3
print(a)

tensor([[3, 3],
        [3, 3]])
tensor([[9, 9],
        [9, 9]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[27., 27.],
        [27., 27.]])


In [104]:
# exp
a = torch.exp(torch.ones(2, 2))

print(a)

a = a.log() # 默认以 e 为底
print(a)

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[1., 1.],
        [1., 1.]])


In [109]:
# floor ceil trunc: 整数 frac: 小数 round: 四舍五入

# clamp
grad = torch.rand(2, 3) * 15

print(grad.max())
print(grad.median())
print(grad.clamp(10))
print(grad)

torch.clamp()

tensor(14.1355)
tensor(6.1030)
tensor([[10.9677, 10.0000, 10.0000],
        [11.8371, 10.0000, 14.1355]])
tensor([[10.9677,  6.0930,  6.1030],
        [11.8371,  2.0998, 14.1355]])


### Tensor 自动广播机制

In [113]:
a = torch.ones(3, 1, 2)
b = torch.ones(2, 1)

print(a.shape)
print(b.shape)

# 2, 1 => 1, 2, 1 => 3, 2, 1 => 3, 2, 2
# 3, 1, 2 => 3, 2, 2
# + => 3, 2, 2
print(torch.add(a, b).shape)

torch.Size([3, 1, 2])
torch.Size([2, 1])
torch.Size([3, 2, 2])
