## Tensor 基础知识

### Tensor 数据类型

In [1]:
import torch

In [4]:
a = torch.Tensor(2, 2)
b = a.int()
c = a.type(torch.DoubleTensor)
d = a.type_as(b)

print(a)
print(b)
print(c)
print(d)

tensor([[2.3694e-38, 4.5908e-41],
        [0.0000e+00, 0.0000e+00]])
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
tensor([[2.3694e-38, 4.5908e-41],
        [0.0000e+00, 0.0000e+00]], dtype=torch.float64)
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


### Tensor 的创建与维度查看

In [9]:
a = torch.Tensor(2, 2)
b = torch.DoubleTensor(2, 2)
print(a)
print(b)

tensor([[ 7.2881e-37,  2.9952e-30],
        [-1.9043e-35,  4.5908e-41]])
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [10]:
c = torch.Tensor([[1, 2], [3, 4]])
print(c)

tensor([[1., 2.],
        [3., 4.]])


In [11]:
d1 = torch.zeros(2, 2)
d2 = torch.eye(2, 2)
d3 = torch.randn(2, 2)
print(d1)
print(d2)
print(d3)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[-2.1773, -0.7162],
        [-1.4039,  0.6929]])


In [15]:
e1 = torch.arange(2, 10, 2)
e2 = torch.linspace(2, 10, 4) # 2 - 10 之前均分 4 份， 8 / 3 = 2.6667
e3 = torch.randperm(6)

print(e1)
print(e2)
print(e3)

tensor([2, 4, 6, 8])
tensor([ 2.0000,  4.6667,  7.3333, 10.0000])
tensor([0, 4, 5, 1, 2, 3])


In [17]:
f1 = torch.tensor([1, 2, 3]) # 类型仍然为 int
f2 = torch.Tensor([1, 2, 3]) # 
print(f1)
print(f2)

tensor([1, 2, 3])
tensor([1., 2., 3.])


In [18]:
g1 = torch.Tensor(2, 2)
g2 = torch.randperm(6)
g3 = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(g1.shape)
print(g2.size())
print(g3.numel()) # 查看总元素的个数
print(g3.nelement())

torch.Size([2, 2])
torch.Size([6])
6
6
